# Generated by Django 2.2.5 on 2019-10-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=300, null=True)),
                ('music_1', models.CharField(max_length=500)),
                ('music_2', models.CharField(max_length=500)),
                ('music_3', models.CharField(max_length=500)),
                ('link_1', models.URLField()),
                ('link_2', models.URLField()),
                ('link_3', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Anger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('tag_1', models.CharField(max_length=500, null=True)),
                ('tag_2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Disgust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('tag_1', models.CharField(max_length=500, null=True)),
                ('tag_2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('tag_1', models.CharField(max_length=500, null=True)),
                ('tag_2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Happiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('tag_1', models.CharField(max_length=500, null=True)),
                ('tag_2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sadness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('subclass_s', models.IntegerField(default=0)),
                ('tag_1', models.CharField(max_length=500, null=True)),
                ('tag_2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subclass_Sad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subclass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Surprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.CharField(max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('tag_1', models.CharField(max_length=500, null=True)),
                ('tag_2', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
