# Generated by Django 2.2.5 on 2019-10-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis_result',
            old_name='link_1',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='analysis_result',
            old_name='music_1',
            new_name='music',
        ),
        migrations.RemoveField(
            model_name='analysis_result',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='analysis_result',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='analysis_result',
            name='music_2',
        ),
        migrations.RemoveField(
            model_name='analysis_result',
            name='music_3',
        ),
        migrations.AddField(
            model_name='analysis_result',
            name='tag_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analysis_result',
            name='tag_2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
