# Generated by Django 2.2 on 2019-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('music_r1', models.IntegerField(default=0)),
                ('music_r2', models.IntegerField(default=0)),
                ('music_r3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Anger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_a', models.CharField(max_length=500)),
                ('age_a', models.IntegerField(default=0)),
                ('link_a', models.URLField()),
                ('tag_a1', models.CharField(max_length=500, null=True)),
                ('tag_a2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_c', models.CharField(max_length=500)),
                ('link_c', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Disgust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_d', models.CharField(max_length=500)),
                ('age_d', models.IntegerField(default=0)),
                ('link_d', models.URLField()),
                ('tag_d1', models.CharField(max_length=500, null=True)),
                ('tag_d2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_f', models.CharField(max_length=500)),
                ('age_f', models.IntegerField(default=0)),
                ('link_f', models.URLField()),
                ('tag_f1', models.CharField(max_length=500, null=True)),
                ('tag_f2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Happiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_h', models.CharField(max_length=500)),
                ('age_h', models.IntegerField(default=0)),
                ('link_h', models.URLField()),
                ('tag_h1', models.CharField(max_length=500, null=True)),
                ('tag_h2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_l', models.CharField(max_length=500)),
                ('link_l', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sadness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_s', models.CharField(max_length=500)),
                ('age_s', models.IntegerField(default=0)),
                ('link_s', models.URLField()),
                ('subclass_s', models.IntegerField(default=0)),
                ('tag_s1', models.CharField(max_length=500, null=True)),
                ('tag_s2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subclass_Sad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subclass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Surprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_su', models.CharField(max_length=500)),
                ('age_su', models.IntegerField(default=0)),
                ('link_su', models.URLField()),
                ('tag_su1', models.CharField(max_length=500, null=True)),
                ('tag_su2', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('research', models.IntegerField(default=0)),
            ],
        ),
    ]
