# Generated by Django 2.2 on 2019-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Information',
        ),
        migrations.RemoveField(
            model_name='analysis_result',
            name='email',
        ),
        migrations.AddField(
            model_name='analysis_result',
            name='user_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis_result',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analysis_result',
            name='music_r1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='analysis_result',
            name='music_r2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='analysis_result',
            name='music_r3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anger',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disgust',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fear',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='happiness',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sadness',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subclass_sad',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surprise',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
