# Generated by Django 2.1.7 on 2019-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0002_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Anger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_a', models.CharField(max_length=500)),
                ('link_a', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Disgust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_d', models.CharField(max_length=500)),
                ('link_d', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_f', models.CharField(max_length=500)),
                ('link_f', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Happiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_h', models.CharField(max_length=500)),
                ('link_h', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sadness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_s', models.CharField(max_length=500)),
                ('link_s', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subclass_Sad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Surprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_su', models.CharField(max_length=500)),
                ('link_su', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Emotion',
            new_name='Emotion_Information',
        ),
        migrations.RemoveField(
            model_name='music',
            name='emotion_id',
        ),
        migrations.RenameField(
            model_name='emotion_information',
            old_name='emotion',
            new_name='emotion_name',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
