# Generated by Django 2.2 on 2019-04-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0003_auto_20190416_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anger',
            name='link_a',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='disgust',
            name='link_d',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='fear',
            name='link_f',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='happiness',
            name='link_h',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sadness',
            name='link_s',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='surprise',
            name='link_su',
            field=models.URLField(),
        ),
    ]
