# Generated by Django 2.2 on 2019-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0003_auto_20190413_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Anger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_a', models.CharField(max_length=500)),
                ('link_a', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Disgust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_d', models.CharField(max_length=500)),
                ('link_d', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_f', models.CharField(max_length=500)),
                ('link_f', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Happiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_h', models.CharField(max_length=500)),
                ('link_h', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sadness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_s', models.CharField(max_length=500)),
                ('link_s', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subclass_Sad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Surprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_su', models.CharField(max_length=500)),
                ('link_su', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='emotion_information',
            name='emotion_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='nickname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
