# Generated by Django 2.2 on 2019-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0005_auto_20190507_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_lie', models.CharField(max_length=500)),
                ('link_lie', models.URLField()),
            ],
        ),
    ]
