# Generated by Django 2.2 on 2019-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0006_lie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_c', models.CharField(max_length=500)),
                ('link_c', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comments_List',
        ),
        migrations.DeleteModel(
            name='Emotion_Information',
        ),
        migrations.RenameField(
            model_name='analysis_result',
            old_name='nickname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='lie',
            old_name='link_lie',
            new_name='link_l',
        ),
        migrations.RenameField(
            model_name='lie',
            old_name='music_lie',
            new_name='music_l',
        ),
        migrations.RenameField(
            model_name='user_information',
            old_name='nickname',
            new_name='email',
        ),
        migrations.AddField(
            model_name='anger',
            name='tag_a1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='anger',
            name='tag_a2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disgust',
            name='tag_d1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disgust',
            name='tag_d2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fear',
            name='tag_f1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fear',
            name='tag_f2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='happiness',
            name='tag_h1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='happiness',
            name='tag_h2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sadness',
            name='tag_s1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sadness',
            name='tag_s2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='surprise',
            name='tag_su1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='surprise',
            name='tag_su2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
