# Generated by Django 2.2 on 2019-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mood_music', '0007_auto_20190524_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='anger',
            name='age_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disgust',
            name='age_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fear',
            name='age_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='happiness',
            name='age_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sadness',
            name='age_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surprise',
            name='age_su',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysis_result',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
